add version pins to Dockerfile

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,21 +1,22 @@
+# this image gets published to GHCR for production use
 ARG build_for=linux/amd64
 ARG py_version=3.10.7
-ARG dbt_snowflake_ref=dbt-snowflake@main
-
 
 FROM --platform=$build_for python:$py_version-slim-bullseye as base
 
 RUN apt-get update \
   && apt-get dist-upgrade -y \
   && apt-get install -y --no-install-recommends \
-    git \
-    ssh-client \
-    software-properties-common \
-    make \
-    build-essential \
-    ca-certificates \
-    libpq-dev \
-  && apt-get clean \
+    build-essential=12.9 \
+    ca-certificates=20210119 \
+    git=1:2.30.2-1+deb11u2 \
+    libpq-dev=13.14-0+deb11u1 \
+    make=4.3-4.1 \
+    openssh-client=1:8.4p1-5+deb11u3 \
+    software-properties-common=0.96.20.2-2.1
+
+# cleanup
+RUN apt-get clean \
   && rm -rf \
     /var/lib/apt/lists/* \
     /tmp/* \
@@ -27,45 +28,13 @@ ENV LANG=C.UTF-8
 RUN python -m pip install --upgrade pip setuptools wheel --no-cache-dir
 
 
-# this image gets published to GHCR for production use
 FROM base as dbt-snowflake
+
+ARG dbt_snowflake_ref=dbt-snowflake@main
+
+HEALTHCHECK CMD dbt --version || exit 1
 
 WORKDIR /usr/app/dbt/
 ENTRYPOINT ["dbt"]
 
 RUN python -m pip install --no-cache-dir "dbt-snowflake @ git+https://github.com/dbt-labs/${dbt_snowflake_ref}"
-
-HEALTHCHECK CMD dbt --version || exit 1
-
-
-# this image does not get published, it is intended for local development only, see `Makefile` for usage
-FROM base as dbt-snowflake-dev
-
-RUN apt-get update \
-  && apt-get install -y --no-install-recommends \
-        git-all \
-        libbz2-dev \
-        libffi-dev \
-        libgdbm-dev \
-        libncurses5-dev \
-        libnss3-dev \
-        libreadline-dev \
-        libsqlite3-dev \
-        libssl-dev \
-        wget \
-        zlib1g-dev \
-  && apt-get clean \
-  && rm -rf \
-    /var/lib/apt/lists/* \
-    /tmp/* \
-    /var/tmp/*
-
-# setup mount for local code
-WORKDIR /opt/code
-VOLUME /opt/code
-
-ENTRYPOINT ["python", "-m", "pip", "install", "--no-cache-dir", "-e", ".", "-r dev-requirements.txt", "&&", "pre-commit install"]
-
-HEALTHCHECK CMD dbt --version || exit 1
-
-ENV PYTHONUNBUFFERED=1
